#! /bin/sh


pgrep -x sxhkd > /dev/null || sxhkd &
xrandr --output DP-2 --mode 2560x1440 -r 240.00 --primary --right-of DP-0 --output DP-0 --mode 2560x1440 -r 120.00

bspc monitor DP-2 -d 1 2 3 4 5 6 7 8
bspc monitor DP-0 -d 9
bspc wm --reorder-monitors DP-2 DP-0
bspc monitor -f DP-2

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color '#fdf6e3'
bspc config focused_border_color '#0d667d'
bspc config gapless_monocle false


bspc rule -a Gimp desktop='^8' state=floating follow=off
bspc rule -a Chromium desktop='^4'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam desktop='^9' state=tiled follow=off
bspc rule -a Emacs state=tiled
bspc rule -a Terminator state=tiled


#xrdb ~/.Xresources
#compton --config ~/compton.conf &
#feh --bg-scale dotfiles/wallpapers/firewatch-blue.jpg &
#polybar example &
#xinput --set-prop 10 'Device Accel Profile' -1 &
#xset s 0 s blank &
#xset -dpms &
#xrandr -r 120 &
#xsetroot -cursor_name left_ptr &
#gsettings set org.gnome.desktop.background show-desktop-icons false &
#emacs --daemon
feh --bg-scale dotfiles/wallpapers/nms.png &
xset s 0 s blank &
xset -dpms &
