#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Steam desktop='^9' state=floating follow=off
bspc rule -a Emacs state=tiled
bspc rule -a Terminator state=tiled

compton --config ~/compton.conf &
feh --bg-scale dotfiles/wallpapers/firewatch-blue.jpg &
xinput --set-prop 10 'Device Accel Profile' -1 &
polybar example
